# Exports a YAML with relevant information about recently modified instances
resource "local_file" "instances_information" {
  sensitive_content = local.instances_information_yaml
  filename = "${path.module}/autogenerated/instances_information.yaml"
}