locals {

  # Instances network definition
  networks = {
    # Instances connection type
    # Values: nat (default), macvtap
    mode = "nat"

    # Configuration for NAT
    nat = {
      # Assignable IP address blocks in CIDR notation
      # Example: [IPv4/CIDR]
      addresses = ["10.17.3.0/24"]

      # Address to the gateway
      gateway_ipv4 = "10.17.3.1"
    }

    # Configuration for macvtap
    macvtap = {
      # Host physical interface to attach
      # the autogenerated virtual interface
      interface = "eno1"

      # Address to the gateway
      gateway_ipv4 = "192.168.0.1"
    }
  }

  # Instance basic definition.
  # WARNING: Choose IP a address inside the right subnet
  instances = {

    # Define the masters
#    kube-master-0 = {
#      memory = 2048 #2GB
#      vcpu = 2
#      addresses = ["192.168.0.210/32"] #CIDR notation
#      gateway4 = "192.168.0.1"
#    }
#
#    kube-master-1 = {
#      memory = 2048 #2GB
#      vcpu = 2
#      addresses = ["192.168.0.211/32"] #CIDR notation
#      gateway4 = "192.168.0.1"
#    }
#
#    # Define the workers
#    kube-worker-0 = {
#      memory = 2048 #2GB
#      vcpu = 2
#      addresses = ["192.168.0.220/32"] #CIDR notation
#      gateway4 = "192.168.0.1"
#    }

    # Define the workers
    kube-worker-0 = {
      memory = 2048 #2GB
      vcpu = 2
      addresses = ["10.17.3.100/24"]
    }

  }



}
